# Melee Goblin
MELEE_GOBLIN_NAME = "Melee Goblin"
MELEE_GOBLIN_HP = 50
MELEE_GOBLIN_MIN_DMG = 5
MELEE_GOBLIN_MAX_DMG = 20
MELEE_GOBLIN_ARMOR = 20
MELEE_GOBLIN_RANGE = 1
MELEE_GOBLIN_MIN_POSITION = 1
MELEE_GOBLIN_MAX_POSITION = 3

# Ranged Goblin
RANGED_GOBLIN_NAME = "Ranged Goblin"
RANGED_GOBLIN_HP = 40
RANGED_GOBLIN_MIN_DMG = 5
RANGED_GOBLIN_MAX_DMG = 15
RANGED_GOBLIN_ARMOR = 15
RANGED_GOBLIN_RANGE = 7
RANGED_GOBLIN_MIN_POSITION = 3
RANGED_GOBLIN_MAX_POSITION = 6

# Knight
KNIGHT_NAME = "Knight"
KNIGHT_HP = 150
KNIGHT_MIN_DMG = 10
KNIGHT_MAX_DMG = 25
KNIGHT_ARMOR = 50
KNIGHT_RANGE = 1

# Archer
ARCHER_NAME = "Archer"
ARCHER_HP = 100
ARCHER_MIN_DMG = 15
ARCHER_MAX_DMG = 30
ARCHER_ARMOR = 10
ARCHER_RANGE = 5

# Mage
MAGE_NAME = "Mage"
MAGE_HP = 80
MAGE_MIN_DMG = 20
MAGE_MAX_DMG = 45
MAGE_ARMOR = 5
MAGE_RANGE = 4
MAGE_HEAL = 30