# stats.py
MELEE_GOBLIN_NAME = "Melee Goblin"
MELEE_GOBLIN_HP = 50
MELEE_GOBLIN_ATTACK_RANGE = (5, 20)
MELEE_GOBLIN_ARMOR = 20
MELEE_GOBLIN_RANGE = 1
MELEE_GOBLIN_POSITION_RANGE = (1, 3)

RANGED_GOBLIN_NAME = "Ranged Goblin"
RANGED_GOBLIN_HP = 40
RANGED_GOBLIN_ATTACK_RANGE = (5, 15)
RANGED_GOBLIN_ARMOR = 15
RANGED_GOBLIN_RANGE = 7
RANGED_GOBLIN_POSITION_RANGE = (3, 6)


KNIGHT_CLASS = "Knight"
KNIGHT_HP = 150
KNIGHT_DAMAGE_RANGE = (10, 25)
KNIGHT_ARMOR = 50
KNIGHT_RANGE = 1

ARCHER_CLASS = "Archer"
ARCHER_HP = 100
ARCHER_ATTACK_RANGE = (15, 30)
ARCHER_ARMOR = 10
ARCHER_RANGE = 5

MAGE_CLASS = "Mage"
MAGE_HP = 80
MAGE_ATTACK_RANGE = (20, 45)
MAGE_ARMOR = 5
MAGE_RANGE = 4
MAGE_HEAL = 30
